import Head from 'next/head';
import { useEffect, useState } from 'react';
import {
  GridContainer,
  fadeInUpAnimation,
  GridItem,
  MainTitle,
} from '../src/commons/styles/mainStyles';

const images = [
  'img/main_cat1.jpg',
  'img/main_cat2.jpg',
  'img/main_cat3.jpg',
  'img/main_cat4.jpg',
];

export default function Home(): JSX.Element {
  const [imageLoaded, setImageLoaded] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => {
      setImageLoaded(true);
    }, 100); // Delay to ensure animations start correctly
    return () => clearTimeout(timer);
  }, []);

  return (
    <>
      <Head>
        <title>Codekat Freeboard Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="img/codekat.ico" />
      </Head>

      <style>{fadeInUpAnimation}</style>

      <MainTitle>MAIN PAGE</MainTitle>

      <GridContainer>
        {images.map((src, index) => (
          <GridItem key={index} delay={imageLoaded ? index * 0.5 : 0}>
            <img src={src} alt={`main-cat${index + 1}`} />
          </GridItem>
        ))}
      </GridContainer>
    </>
  );
}
