import Head from 'next/head';
import styled from '@emotion/styled';

const GridContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  grid-gap: 10px;
  width: 80%;
  margin: 0 auto;
`;

const GridItem = styled.div`
  img {
    width: 100%;
    height: auto;
  }
`;

const images = [
  'img/main-cat1.png',
  'img/main-cat2.png',
  'img/main-cat3.png',
  'img/main-cat4.png',
];

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Codekat Freeboard Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="img/codekat.ico" />
      </Head>

      <GridContainer>
        {images.map((src, index) => (
          <GridItem key={index}>
            <img src={src} alt={`main-cat${index + 1}`} />
          </GridItem>
        ))}
      </GridContainer>
    </>
  );
}
